[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Repository for a GenAI backend"
authors = []
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
langchain = "0.1.16"
langchain_community = "0.0.32"
pypdf = ">=4.0.0"
langchain-google-vertexai = "1.0.3"
langchain-google-community = "1.0.3"
python-multipart =">=0.0.10"
fastapi = "0.109"
uvicorn = {extras = ["standard"], version = "0.29.0"}
